### ISSUE TITLE
User can view the landing page and sign up for Sprig

### ISSUE THREAD

**Issue by lucymar** [sprig-io/Sprig#1]
SUBTASKS:
- [x] create boiler plate #6 
- [ ] create unit tests #14 
- [x] create mongoDB account with admin and users
- [x] define user collection
- [x] create express post route to add a new user
- [ ] create express user get route
- [ ] create redux store/thunks for posting user and getting user
- [ ] create react component for sign-up flow (landing page) #22
- [ ] create react component that shows logged-in state #16 
- [ ] connect react with redux for login page #20
- [ ] landing page with the get started button #21
