### ISSUE TITLE
User can link one or more banks to their sprig account

### ISSUE THREAD

**Issue by lucymar** [sprig-io/Sprig#2]
- [x] research plaid #8
- [x] create mongo db schema and review with team #7
- [x] integrate plaid api keys/access (dependent on #6) #11
- [x] create database route for adding accounts via plaid  #10
- [x] create oauth front-end component for adding accounts via plaid #9
- [x] needs to be fixed: adding accounts after refreshing page #28
- [ ] create tests for adding accounts #29
