### ISSUE TITLE
Dashboard - user can view insights about monthly subscriptions and unnecessary fees

### ISSUE THREAD

**Issue by lucymar** [sprig-io/Sprig#4]
- [x] Write utility function for calculating number of monthly fees (success === console.logging info) #35
- [x] Write utility function for calculating amount spent on taxis in last month #36
- [x] Write utility function for calculating merchant where user spent the most money that month #37
- [ ] Write a utility function for calculating banking fees #38
- [ ] Create redux actions/thunks for rendering each utility function #39
- [ ] Create front end react component for showing insights as a carousel/cards that the user can flip through #40
-[ ] create new backend route for monthly data #47 
- [ ] Write utility function to calculate amount spent on banking fees #44
